function out1 = define_X(t)
%DEFINE_X
%    OUT1 = DEFINE_X(T)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    22-Jan-2018 20:31:28

t2 = sin(t);
t3 = cos(t);
t4 = t.*pi.*(1.0./5.0);
t5 = t.*2.0;
out1 = [t2.*t3.*(-1.1e1./5.0e1)-t2.*sin(t4).*(1.0./2.5e1)+t.*pi.*(t3.^2.*2.0-1.0).*(1.1e1./5.0e2),cos(t5).*(1.1e1./1.0e2)-t2.*cos(t4).*(1.0./2.5e1)+t.*pi.*sin(t5).*(1.1e1./5.0e2),0.0];
